version: '3.8'

services:
  postgres:
    image : postgres:14.1-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=Nilva
      - POSTGRES_USER=Nilva
      - POSTGRES_PASSWORD=N!lva
    volumes: 
      - postgres-data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python -m web.manage runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=psql://Nilva:N!lva@postgres:5432/Nilva
      - REDIS_URL=redis://127.0.0.1:6379/0
      - SECRET_KEY=django-insecure-b$7cx%+wcj^8v6fuek@k^j)-oc+72x=ida0aw$n%anxus#us%5
      - DEBUG=True
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    restart: on-failure


volumes:
  postgres-data:
  redis-data:

